
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 648)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 556))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(80, 110, 256, 200))
        self.listWidget.setObjectName("listWidget")
        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ComboBox = QtWidgets.QComboBox(self.tab_2)
        self.ComboBox.setGeometry(QtCore.QRect(40, 70, 86, 25))
        self.ComboBox.setObjectName("ComboBox")
        self.ButtonComboBox = QtWidgets.QPushButton(self.tab_2)
        self.ButtonComboBox.setGeometry(QtCore.QRect(40, 130, 89, 25))
        self.ButtonComboBox.setObjectName("ButtonComboBox")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(320, 20, 441, 461))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.tab_2, "")


        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_SQB = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_SQB.setGeometry(QtCore.QRect(20, 30, 211, 81))
        self.pushButton_SQB.setObjectName("SelectQueryButton")


        self.groupBoxQPRICE = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxQPRICE.setGeometry(QtCore.QRect(250, 30, 150, 80))
        self.groupBoxQPRICE.setObjectName("groupBoxTabT3")
        self.radioButN = QtWidgets.QRadioButton(self.groupBoxQPRICE)
        self.radioButN.setGeometry(QtCore.QRect(5, 10, 100, 15))
        self.radioButN.setObjectName("radioButN")
        self.radioButB = QtWidgets.QRadioButton(self.groupBoxQPRICE)
        self.radioButB.setGeometry(QtCore.QRect(5, 30, 150, 15))
        self.radioButB.setObjectName("radioButB")
        self.radioButM = QtWidgets.QRadioButton(self.groupBoxQPRICE)
        self.radioButM.setGeometry(QtCore.QRect(5, 50, 150, 15))
        self.radioButM.setObjectName("radioButM")

        self.groupBoxCheck = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxCheck.setGeometry(QtCore.QRect(410, 30, 150, 80))
        self.groupBoxCheck.setObjectName("groupBoxCheck")
        self.check_date = QtWidgets.QCheckBox(self.groupBoxCheck)
        self.check_date.setGeometry(QtCore.QRect(5, 15, 120, 20))
        self.check_date.setObjectName("groupBoxCheck")
        self.check_phone = QtWidgets.QCheckBox(self.groupBoxCheck)
        self.check_phone.setGeometry(QtCore.QRect(5, 45, 120, 20))
        self.check_phone.setObjectName("groupBoxCheck")

        self.groupBoxT3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxT3.setGeometry(QtCore.QRect(20, 130, 370, 300))
        self.groupBoxT3.setObjectName("groupBoxTabT3")
        self.LabelCTName = QtWidgets.QLabel(self.groupBoxT3)
        self.LabelCTName.setGeometry(QtCore.QRect(40, 70, 86, 25))
        self.LabelCTName.setObjectName("LabelCTName")
        self.ComboBoxT3Tname = QtWidgets.QComboBox(self.groupBoxT3)
        self.ComboBoxT3Tname.setGeometry(QtCore.QRect(40, 100, 86, 25))
        self.ComboBoxT3Tname.setObjectName("ComboBoxT3Tname")
        self.LabelCinfo = QtWidgets.QLabel(self.groupBoxT3)
        self.LabelCinfo.setGeometry(QtCore.QRect(120, 20, 100, 25))
        self.LabelCinfo.setObjectName("LabelCinfo")
        self.LabelCCName = QtWidgets.QLabel(self.groupBoxT3)
        self.LabelCCName.setGeometry(QtCore.QRect(170, 70, 100, 25))
        self.LabelCCName.setObjectName("LabelCTName")
        self.ComboBoxT3Cname = QtWidgets.QComboBox(self.groupBoxT3)
        self.ComboBoxT3Cname.setGeometry(QtCore.QRect(150, 100, 100, 25))
        self.ComboBoxT3Cname.setObjectName("ComboBoxT3Cname")

        self.groupBoxT3Q = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxT3Q.setGeometry(QtCore.QRect(400, 130, 370, 300))
        self.groupBoxT3Q.setObjectName("groupBoxT3Q")
        self.ReqLine = QtWidgets.QLineEdit(self.groupBoxT3Q)
        self.ReqLine.setGeometry(QtCore.QRect(75, 120, 220, 30))
        self.ReqLine.setObjectName("ReqLine")
        self.pushButton_FIND = QtWidgets.QPushButton(self.groupBoxT3Q)
        self.pushButton_FIND.setGeometry(QtCore.QRect(140, 220, 100, 50))
        self.pushButton_FIND.setObjectName("pushButton_FIND")

        self.tabWidget.addTab(self.tab_3, "")


        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RGZ_DB"))
        self.pushButton_SQB.setText(_translate("MainWindow", "Выполнить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Просмотр Таблиц"))
        self.ButtonComboBox.setText(_translate("MainWindow", "Select DB"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Добавление Данных"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Выборка"))
        self.radioButN.setText(_translate("MainWindow", "Defolt"))
        self.radioButB.setText(_translate("MainWindow", "Цена >= 1000"))
        self.radioButM.setText(_translate("MainWindow", "Цена < 1000"))
        self.pushButton_FIND.setText(_translate("MainWindow", "Найти"))
        self.LabelCTName.setText(_translate("MainWindow", "Таблица"))
        self.LabelCCName.setText(_translate("MainWindow", "Поле"))
        self.LabelCinfo.setText(_translate("MainWindow", "Поиск"))
        self.check_date.setText(_translate("MainWindow", "Дата"))
        self.check_phone.setText(_translate("MainWindow", "Телефон"))
